### ISSUE TITLE
RF-001: Creación del combate

### ISSUE THREAD

**Issue by j23rl07** [j23rl07/adri-s-bizarre-adventure#34]
# Descripción de la tarea
Creación de las acciones de combate básico del personaje

# Tareas a completar
- [x] Golpe básico a derecha o izquierda
- [x] Sprite de golpear
- [x] Golpe vertical hacia arriba
- [x] Creación de habilidad dummy

# Criterios de validación
- [x] Golpea hacia derecha e izquierda
- [x] Sprite de golpear
- [x] Golpe vertical
- [x] Habilidad dummy creada

**Comment by josaloroc** [comment]
Los resultados se encuentran en la escena "Interfaz"
Se han añadido cada unos de los elementos citados en la checklist aparte de ciertos elementos necesarios para testear
el funcionamiento: dummy de objeto dañable.
