### ISSUE TITLE
RF-002: Interfaz del jugador

### ISSUE THREAD

**Issue by j23rl07** [j23rl07/adri-s-bizarre-adventure#38]
# Descripción de la tarea
Diseño básico de la interfaz del jugador en partida

# Tareas a completar
- [x] Barra de energía
- [x] Barra de concentración
- [x] Slot de magia
- [x] Contador de "pociones de curación"
- [x] Contador de monedas

# Criterios de validación
- [x] Barra de energía visible
- [x] Barra de concentración visible
- [x] Slot de magia visible
- [x] Contador de "pociones de curación" visible
- [x] Contador de monedas visible

**Comment by josaloroc** [comment]
Los resultados se encuentran en la escena "Interfaz"
Se han añadido cada unos de los elementos citados en  la checklist.
